### ISSUE TITLE
chore: enable search

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/docs-v2#15]
### Problem

Something we had in our old docs is this search box:
<img width="1433" alt="image" src="https://github.com/cowprotocol/docs-v2/assets/2352112/c40443a4-a0e8-4936-a5b1-092437e42712">

I see new docs don't have it yet:
<img width="1424" alt="image" src="https://github.com/cowprotocol/docs-v2/assets/2352112/58185d14-0fa4-4189-95e6-243d936f1a35">

This is really a feature DEVs use and make it more user friendly, it would be nice to not loose this feature.

There's a page related to this in docusaurus:
https://docusaurus.io/docs/search

I would be great to have this feature in the new docs.

**Comment by mfw78** [comment]
Using the officially supported docs search engine ([Agolia Docsearch](https://docusaurus.io/docs/next/search#using-algolia-docsearch)) requires that the documentation already be done and complete (no placeholder content etc). Application processes then take approximately 2 weeks, so it's likely docs would initially launch _without_ this, but it would be enabled when the documentation is done / crawled.

Alternatives include running our own infra for this, but I think we shouldn't do this if there exists other infra already.

**Comment by anxolin** [comment]
This is definetly enough! 

> Alternatives include running our own infra for this, but I think we shouldn't do this if there exists other infra already.

I think is not needed at first. Thanks for looking into it

**Comment by mfw78** [comment]
Fixed in #196
