### ISSUE TITLE
chore: port new EIP-1271 security page from old docs 

### ISSUE THREAD

**Issue by fedgiac** [cowprotocol/docs-v2#23]
### Background
We added a new [security-related page](https://github.com/cowprotocol/docs/commit/89799d70c4624f9b3aa516dbf4caf92448e497c0) to the old docs.

### Details
We should include the new page in the docs v2. As this involves a security issue, it's important to keep users informed about it.

### Acceptance criteria

- [ ] EIP-1271 security issue is fully documented in the docs v2.

**Comment by mfw78** [comment]
Duplicate, monitored in #147
