### ISSUE TITLE
docs(cow-sdk): eth flow docs

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/docs-v2#8]

**Comment by alfetopito** [comment]
Is this covered by https://beta.docs.cow.fi/cow-protocol/tutorials/cow-swap/native#use-eth-flow ?

**Comment by mfw78** [comment]
> Is this covered by https://beta.docs.cow.fi/cow-protocol/tutorials/cow-swap/native#use-eth-flow ?

I think this would be more how to do Eth-Flow using the `cow-sdk` (and therefore be a tutorial in https://github.com/cowprotocol/tutorial) ?

Though, having said this, I did copy this from the brain dump to get all the docs out from other repositories (eg. cow-sdk)

**Comment by alfetopito** [comment]
Ah, my bad. I missed the obvious `cow-sdk` tag 🤦

**Comment by alfetopito** [comment]
Actually, the eth-flow contract is not usable from the sdk
